version: '3'
services:
  express-app:
    build:
      context: "."
      dockerfile: "Dockerfile"
    tty: true
    ports:
      - 5000:5000
    volumes:
      - ./express-app:/express-app
    user: ${UID_GID}
